
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfy-watcher
  labels:
    app: comfy-watcher
spec:
  replicas: {{ .Values.replicaCount.watcher }}
  selector:
    matchLabels:
      app: comfy-watcher
  template:
    metadata:
      labels:
        app: comfy-watcher
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      initContainers:
        - name: wait-for-comfyui
          image: busybox:1.35
          command: ['sh', '-c']
          args:
            - |
              until wget --quiet --tries=1 --timeout=3 --spider http://localhost:8188/system_stats || exit 1; do
                echo "Waiting for ComfyUI to be ready..."
                sleep 5
              done
              echo "ComfyUI is ready!"
      containers:
        - name: comfyui
          image: "{{ .Values.image.comfyui.repository }}:{{ .Values.image.comfyui.tag }}"
          imagePullPolicy: {{ .Values.image.comfyui.pullPolicy }}
          command: ["python", "main.py"]
          args: ["{{ .Values.environment.comfyui.extraArgs }}"]
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "compute,utility"
          ports:
            - containerPort: 8188
              name: http
          resources:
            requests:
              memory: {{ .Values.resources.comfyui.requests.memory }}
              nvidia.com/gpu: {{ .Values.resources.comfyui.requests["nvidia.com/gpu"] }}
          readinessProbe:
            httpGet:
              path: /system_stats
              port: 8188
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /system_stats
              port: 8188
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: models
              mountPath: {{ .Values.persistence.hostPath.models }}
            - name: custom-nodes
              mountPath: {{ .Values.persistence.hostPath.customNodes }}
            - name: output
              mountPath: {{ .Values.persistence.hostPath.output }}
          securityContext:
            runAsUser: {{ .Values.environment.comfyui.userId }}
            runAsGroup: {{ .Values.environment.comfyui.groupId }}
        - name: comfy-watcher
          image: "{{ .Values.image.watcher.repository }}:{{ .Values.image.watcher.tag }}"
          imagePullPolicy: {{ .Values.image.watcher.pullPolicy }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.environment.application.logLevel | quote }}
            - name: OUTPUT_FOLDER
              value: {{ .Values.environment.application.outputFolder | quote }}
            - name: COMFYUI_URL
              value: "http://localhost:8188"
            - name: POLL_INTERVAL
              value: {{ .Values.environment.application.fastQueuePollInterval | quote }}
            - name: AWS_DEFAULT_REGION
              value: {{ .Values.environment.aws.region | quote }}
            - name: COMFY_AWS_DEFAULT_REGION
              value: {{ .Values.environment.aws.region | quote }}
            - name: AWS_ROLE_NAME
              value: {{ .Values.environment.aws.roleName | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: accessKeyId
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: secretAccessKey
          resources:
            requests:
              memory: {{ .Values.resources.watcher.requests.memory }}
            limits:
              memory: {{ .Values.resources.watcher.limits.memory }}
          volumeMounts:
            - name: output
              mountPath: {{ .Values.environment.application.outputFolder }}
      volumes:
        - name: models
          hostPath:
            path: {{ .Values.persistence.hostPath.models }}
        - name: custom-nodes
          hostPath:
            path: {{ .Values.persistence.hostPath.customNodes }}
        - name: output
          hostPath:
            path: {{ .Values.persistence.hostPath.output }}
      nodeSelector:
        nvidia.com/gpu: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu
                    operator: Exists
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      restartPolicy: Always