version: '3.8'

services:
  comfy-watcher:
    image: jeffmittens/comfy-watcher:latest
    environment:
      # AWS Configuration
      - AWS_ACCESS_KEY_ID_FILE=/run/secrets/aws_access_key_id
      - AWS_SECRET_ACCESS_KEY_FILE=/run/secrets/aws_secret_access_key
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-west-2}

      # ComfyUI Configuration
      - COMFY_HOST=${COMFY_HOST:-comfyui}
      - COMFY_PORT=${COMFY_PORT:-8188}
      
      # Application Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - POLL_INTERVAL=${POLL_INTERVAL:-2}
      - OUTPUT_FOLDER=/app/output
    volumes:
      - /opt/comfyui/output:/app/output
    secrets:
      - aws_secret_access_key
      - aws_access_key_id
    depends_on:
      - comfyui
    restart: unless-stopped
    networks:
      - comfy-network

  comfyui:
    # Replace with your ComfyUI container image
    image: ghcr.io/lecode-official/comfyui-docker:latest
    ports:
      - "8188:8188"
    volumes:
      - /opt/comfyui/models:/opt/comfyui/models:rw
      - /opt/comfyui/custom_nodes:/opt/comfyui/custom_nodes:rw
      - /opt/comfyui/output:/opt/comfyui/output:rw
    environment:
      USER_ID: "1000"
      GROUP_ID: "1000"
      EXTRA_ARGS: "--listen 0.0.0.0 --disable-smart-memory"
    restart: unless-stopped
    networks:
      - comfy-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

    runtime: nvidia

networks:
  comfy-network:
    driver: bridge

secrets:
  comfy_aws_access_key_id:
    file: ./secrets/aws_access_key_id.txt
  comfy_aws_secret_access_key:
    file: ./secrets/aws_secret_access_key.txt
  comfy_aws_s3_bucket:
    file: ./secrets/aws_s3_bucket.txt
  comfy_aws_sqs_name:
    file: ./secrets/aws_sqs_name.txt
