version: '3.8'

services:
  comfy-watcher:
    image: jeffmit/comfy-watcher:latest
    environment:
      # AWS Configuration
      - COMFY_AWS_ACCESS_KEY_ID_FILE=/run/secrets/comfy_aws_access_key_id
      - COMFY_AWS_SECRET_ACCESS_KEY_FILE=/run/secrets/comfy_aws_secret_access_key
      - COMFY_AWS_DEFAULT_REGION=${COMFY_AWS_DEFAULT_REGION:-us-west-2}
      - COMFY_AWS_S3_BUCKET=${COMFY_AWS_S3_BUCKET}
      - COMFY_AWS_SQS_NAME=${COMFY_AWS_SQS_NAME}
      
      # ComfyUI Configuration
      - COMFY_HOST=${COMFY_HOST:-comfyui}
      - COMFY_PORT=${COMFY_PORT:-8188}
      
      # Application Configuration
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - POLL_INTERVAL=${POLL_INTERVAL:-2}
      - OUTPUT_FOLDER=/app/output
    volumes:
      - comfy_output:/app/output
    secrets:
      - comfy_aws_access_key_id
      - comfy_aws_secret_access_key
    depends_on:
      - comfyui
    restart: unless-stopped
    networks:
      - comfy-network

  comfyui:
    # Replace with your ComfyUI container image
    image: yanwk/comfyui-boot:latest
    ports:
      - "8188:8188"
    volumes:
      - comfy_models:/app/models
      - comfy_output:/app/output
    environment:
      - CLI_ARGS=--listen 0.0.0.0
    restart: unless-stopped
    networks:
      - comfy-network

volumes:
  comfy_models:
  comfy_output:

networks:
  comfy-network:
    driver: bridge

secrets:
  comfy_aws_access_key_id:
    file: ./secrets/aws_access_key_id.txt
  comfy_aws_secret_access_key:
    file: ./secrets/aws_secret_access_key.txt
