apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfy-models-pvc
  namespace: comfy-watcher
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard # Adjust based on your cluster
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfy-output-pvc
  namespace: comfy-watcher
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard # Adjust based on your cluster
